[package]
name = "primer"
version = "0.1.0"
authors = ["user"]

[dependencies]
#num = "*"
time = "*"
hyper = "*"
rustc-serialize = "*"
#serde_json = "*"
#serde_macros = "*"

[profile.release]
#debug = true
